// ─────────────────────────────────────────────────────────────────────────────
// Mock data for the product prototype (src/app/*).
//
// This is a clickable, front-end-only mockup: everything below is hand-written
// fixture data, not a real API. Shapes mirror what a real backend would return
// so components can be swapped over later without changing their props.
// ─────────────────────────────────────────────────────────────────────────────

import beach from '../assets/img/beach_1.webp'
import foodTable from '../assets/img/food-table.webp'
import riceTerraces from '../assets/img/rice-terraces.jpg'
import templeGarden from '../assets/img/temple-garden.webp'
import restaurant from '../assets/img/restaurant.jpg'
import templeOrnate from '../assets/img/temple-ornate.jpg'
import angkor from '../assets/img/angkor.jpg'

export const CURRENT_USER = {
  id: 'u-dara',
  username: 'dara.explores',
  displayName: 'Dara Ly',
  location: 'Phnom Penh, Cambodia',
  email: 'dara.ly@example.com',
  bio: 'Weekend wanderer. Always chasing sunset spots and street food stalls around the riverside.',
  travelStyleTags: ['Foodie', 'Backpacker', 'Night Owl'],
  stats: { tripsPublished: 6, placesVisited: 42, tripsLiked: 18 },
  followers: 128,
  following: 76,
  followerPreview: ['Sreymom Chan', 'Vichet Ros', 'Bopha Sok'],
  followingPreview: ['Chenda Pich', 'Ratanak Heng', 'Sreymom Chan'],
}

// ── Places / businesses ──────────────────────────────────────────────────────
// x / y are percentage positions on the mock map canvas (0-100).
export const PLACES = {
  'pl-pagoda': {
    id: 'pl-pagoda',
    name: 'Golden Spire Pagoda',
    category: 'Temple',
    image: templeOrnate,
    x: 38,
    y: 30,
    atmosphere: ['Serene', 'Spiritual', 'Quiet'],
    preferenceMatch: ['Sightseeing', 'Culture'],
    keywords: ['Ornate architecture', 'Morning chanting', 'Shoes-off courtyard'],
    crowdLevel: 'moderate',
    seatAvailability: null,
    entranceFee: '$3',
    visitDuration: '1.5 hrs',
    description: 'A working pagoda known for its gilded roof tiers and a quiet inner courtyard that fills with incense smoke each morning.',
  },
  'pl-riverside': {
    id: 'pl-riverside',
    name: 'Sisowath Quay Riverside Walk',
    category: 'Riverside',
    image: beach,
    x: 62,
    y: 22,
    atmosphere: ['Breezy', 'Scenic', 'Romantic'],
    preferenceMatch: ['Relaxing', 'Photography'],
    keywords: ['Sunset views', 'Boat traffic', 'Street performers'],
    crowdLevel: 'busy',
    seatAvailability: null,
    entranceFee: 'Free',
    visitDuration: '1 hr',
    description: 'A palm-lined promenade along the river where the whole city seems to come out for the evening breeze.',
  },
  'pl-nightmarket': {
    id: 'pl-nightmarket',
    name: 'Night Market Food Court',
    category: 'Market',
    image: foodTable,
    x: 70,
    y: 55,
    atmosphere: ['Lively', 'Bustling', 'Social'],
    preferenceMatch: ['Food', 'Meeting friends'],
    keywords: ['Grilled skewers', 'Shared floor mats', 'Live karaoke stage'],
    crowdLevel: 'busy',
    seatAvailability: 'limited',
    entranceFee: 'Free entry',
    visitDuration: '2 hrs',
    description: 'Mats on the ground, plastic stools, and a wall of food stalls. Go hungry and go loud.',
  },
  'pl-cafe': {
    id: 'pl-cafe',
    name: 'BKK1 Corner Café',
    category: 'Cafe',
    image: restaurant,
    x: 45,
    y: 62,
    atmosphere: ['Cozy', 'Work-friendly', 'Quiet'],
    preferenceMatch: ['Working', 'Studying'],
    keywords: ['Reliable wifi', 'Cold brew', 'Plug sockets at every table'],
    crowdLevel: 'quiet',
    seatAvailability: 'plenty',
    entranceFee: '$2-4 per item',
    visitDuration: '1-2 hrs',
    description: 'A plant-filled corner spot where laptops outnumber conversations most weekday mornings.',
  },
  'pl-lotusgarden': {
    id: 'pl-lotusgarden',
    name: 'Lotus Garden Temple Grounds',
    category: 'Temple & Garden',
    image: templeGarden,
    x: 28,
    y: 58,
    atmosphere: ['Peaceful', 'Lush', 'Quiet'],
    preferenceMatch: ['Relaxing', 'Photography'],
    keywords: ['Lotus ponds', 'Shaded walkways', 'Resident monks'],
    crowdLevel: 'quiet',
    seatAvailability: null,
    entranceFee: '$2',
    visitDuration: '1 hr',
    description: 'Fewer visitors than the main pagodas, with a pond of lotus flowers that opens at first light.',
  },
  'pl-ricefields': {
    id: 'pl-ricefields',
    name: 'Countryside Rice Field Escape',
    category: 'Nature day trip',
    image: riceTerraces,
    x: 15,
    y: 78,
    atmosphere: ['Tranquil', 'Open-air', 'Scenic'],
    preferenceMatch: ['Relaxing', 'Nature'],
    keywords: ['Ox-cart rides', 'Farm-to-table lunch', 'Cycling paths'],
    crowdLevel: 'quiet',
    seatAvailability: null,
    entranceFee: '$5 guided stop',
    visitDuration: 'Half day',
    description: 'An hour outside the city, where the roads narrow and the rice paddies start.',
  },
  'pl-rivergrill': {
    id: 'pl-rivergrill',
    name: 'Riverside Night Grill',
    category: 'Restaurant',
    image: foodTable,
    x: 66,
    y: 34,
    atmosphere: ['Lively', 'Social', 'Casual'],
    preferenceMatch: ['Food', 'Meeting friends'],
    keywords: ['River view seating', 'BBQ platters', 'Live acoustic sets'],
    crowdLevel: 'moderate',
    seatAvailability: 'limited',
    entranceFee: '$8-15 per person',
    visitDuration: '1.5 hrs',
    description: 'Grilled river fish and cold drinks at tables that spill right up to the water.',
  },
  'pl-siemreap': {
    id: 'pl-siemreap',
    name: 'Siem Reap Temple Extension',
    category: 'Heritage add-on (2 days)',
    image: angkor,
    x: 50,
    y: 12,
    atmosphere: ['Awe-inspiring', 'Historic'],
    preferenceMatch: ['Sightseeing', 'Culture'],
    keywords: ['Sunrise tour', 'Ancient temple complex', 'Multi-day extension'],
    crowdLevel: 'busy',
    seatAvailability: null,
    entranceFee: '$37 (1-day pass)',
    visitDuration: '2 days',
    description: 'A short flight from Phnom Penh. Suggested as an add-on if you have extra days.',
  },

  // ── Real venue data (4 Districts dataset) used by the AI Planner's trip
  // packages below. Photos are seeded placeholders (picsum.photos), not real
  // photography of these venues — this app has no photo of them to bundle.
  'pl-eleven-one': {
    id: 'pl-eleven-one',
    name: 'Eleven One Kitchen',
    category: 'Restaurant',
    district: 'Boeung Keng Kang I',
    image: 'https://picsum.photos/seed/eleven-one-kitchen-bkk1/640/480',
    mapsLink: 'https://maps.app.goo.gl/VnWbNrscV9HqF9iYA',
    x: 30, y: 40,
    atmosphere: ['Relaxing', 'Cultural', 'Casual dining'],
    preferenceMatch: ['Food', 'Relaxing'],
    keywords: ['Local khmer food', 'Open 7am-9:30pm', 'Casual brunch spot'],
    crowdLevel: 'moderate',
    seatAvailability: 'plenty',
    entranceFee: '$10-15',
    visitDuration: '1.5 hrs',
    description: 'A relaxed, authentic khmer kitchen in BKK1 that doubles as a casual brunch spot.',
  },
  'pl-langka-lane': {
    id: 'pl-langka-lane',
    name: 'Langka Lane',
    category: 'Activity',
    district: 'Boeung Keng Kang I',
    image: 'https://picsum.photos/seed/langka-lane-bkk1/640/480',
    mapsLink: 'https://maps.app.goo.gl/y67vPgnbWMZnRtLn8',
    x: 45, y: 30,
    atmosphere: ['Lively', 'Scenic', 'Creative'],
    preferenceMatch: ['Meeting friends', 'Photography'],
    keywords: ['Bars and cafes lane', 'Open 24/7', 'Asian, western food and drinks nearby'],
    crowdLevel: 'busy',
    seatAvailability: null,
    entranceFee: '$4-45',
    visitDuration: '1.5 hrs',
    description: 'A lively lane of bars, cafes and murals that gets more social as the evening goes on.',
  },
  'pl-baitong': {
    id: 'pl-baitong',
    name: 'Baitong Cafe',
    category: 'Cafe',
    district: 'Boeung Keng Kang I',
    image: 'https://picsum.photos/seed/baitong-cafe-bkk1/640/480',
    mapsLink: 'https://maps.app.goo.gl/QntmxjBeibNvYANV7',
    x: 35, y: 55,
    atmosphere: ['Premium', 'Creative', 'Scenic'],
    preferenceMatch: ['Relaxing', 'Photography'],
    keywords: ['Dessert and bakery', 'Open 7am-9pm', 'Garden seating'],
    crowdLevel: 'quiet',
    seatAvailability: 'plenty',
    entranceFee: '$3-8',
    visitDuration: '1 hr',
    description: 'A plant-filled bakery cafe with a premium feel, popular for an afternoon dessert break.',
  },
  'pl-bkk-market': {
    id: 'pl-bkk-market',
    name: 'BKK Market',
    category: 'Market',
    district: 'Boeung Keng Kang I',
    image: 'https://picsum.photos/seed/bkk-market-phnom-penh/640/480',
    mapsLink: 'https://maps.app.goo.gl/hPQ64t8iyGXnERdQA',
    x: 55, y: 62,
    atmosphere: ['Lively', 'Local'],
    preferenceMatch: ['Shopping', 'Food'],
    keywords: ['Everyday local market', 'Open 8am-7pm', 'Great for browsing and snacking'],
    crowdLevel: 'busy',
    seatAvailability: 'limited',
    entranceFee: '$1-20',
    visitDuration: '1.5 hrs',
    description: 'A neighborhood market for browsing local goods and grabbing a quick bite between stops.',
  },
  'pl-royal-palace': {
    id: 'pl-royal-palace',
    name: 'Royal Palace',
    category: 'Heritage site',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/royal-palace-phnom-penh/640/480',
    mapsLink: 'https://maps.app.goo.gl/tnp5SMevtSiyXTD5A',
    x: 40, y: 25,
    atmosphere: ['Scenic', 'Cultural'],
    preferenceMatch: ['Sightseeing', 'Culture'],
    keywords: ['Cambodia\'s royal residence', 'Open 8am-5pm', 'Modest dress required'],
    crowdLevel: 'busy',
    seatAvailability: null,
    entranceFee: '$1-10',
    visitDuration: '2 hrs',
    description: 'The official residence of the King of Cambodia, with gilded pavilions open to visitors.',
  },
  'pl-national-museum': {
    id: 'pl-national-museum',
    name: 'National Museum of Cambodia',
    category: 'Museum',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/national-museum-cambodia/640/480',
    mapsLink: 'https://maps.app.goo.gl/aTvXdbbwDqxZyxPu6',
    x: 50, y: 40,
    atmosphere: ['Cultural', 'Scenic'],
    preferenceMatch: ['Sightseeing', 'Culture'],
    keywords: ['Khmer art and sculpture', 'Open 8am-5pm', 'Terracotta courtyard'],
    crowdLevel: 'moderate',
    seatAvailability: null,
    entranceFee: '$0-10',
    visitDuration: '1.5 hrs',
    description: 'The country\'s largest archaeological and cultural collection, housed around a quiet courtyard.',
  },
  'pl-romdeng': {
    id: 'pl-romdeng',
    name: 'Romdeng Restaurant',
    category: 'Restaurant',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/romdeng-restaurant-pp/640/480',
    mapsLink: 'https://maps.app.goo.gl/Es9i96drmmUGKbPF7',
    x: 45, y: 55,
    atmosphere: ['Scenic', 'Lively', 'Casual dining'],
    preferenceMatch: ['Food', 'Culture'],
    keywords: ['Local khmer food', 'Open 6:30am-9pm', 'Trains at-risk youth as staff'],
    crowdLevel: 'moderate',
    seatAvailability: 'plenty',
    entranceFee: '$1-15',
    visitDuration: '1.5 hrs',
    description: 'A garden restaurant serving Khmer classics, run as a training program for at-risk youth.',
  },
  'pl-central-market': {
    id: 'pl-central-market',
    name: 'Central Market',
    category: 'Market',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/central-market-phnom-penh/640/480',
    mapsLink: 'https://maps.app.goo.gl/HmoKKGXudRjiELo66',
    x: 60, y: 65,
    atmosphere: ['Lively'],
    preferenceMatch: ['Shopping', 'Sightseeing'],
    keywords: ['Art deco landmark market', 'Open 7am-5pm', 'Jewelry, clothes and souvenirs'],
    crowdLevel: 'busy',
    seatAvailability: 'limited',
    entranceFee: 'Free entry',
    visitDuration: '1.5 hrs',
    description: 'An art deco domed market hall and Phnom Penh landmark in its own right.',
  },
  'pl-gather-grounds': {
    id: 'pl-gather-grounds',
    name: 'Gather Grounds Coffee and Eatery Riverside',
    category: 'Cafe',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/gather-grounds-riverside-pp/640/480',
    mapsLink: 'https://maps.app.goo.gl/DhFWC7fdMdG6c6fA7',
    x: 65, y: 20,
    atmosphere: ['Creative', 'Cultural', 'Elegant'],
    preferenceMatch: ['Relaxing', 'Photography'],
    keywords: ['Riverside seating', 'Open 6:30am-9:30pm', 'Local khmer food and desserts'],
    crowdLevel: 'quiet',
    seatAvailability: 'plenty',
    entranceFee: '$1-5',
    visitDuration: '1 hr',
    description: 'A riverside cafe with an elegant, unhurried feel — a good first stop of the day.',
  },
  'pl-sushi-lab': {
    id: 'pl-sushi-lab',
    name: 'SuShi LaB',
    category: 'Restaurant',
    district: 'Boeung Keng Kang I',
    image: 'https://picsum.photos/seed/sushi-lab-bkk1/640/480',
    mapsLink: 'https://maps.app.goo.gl/M5TqTaQkq6ho8oQFA',
    x: 40, y: 45,
    atmosphere: ['Fine dining', 'Elegant', 'Cultural'],
    preferenceMatch: ['Food'],
    keywords: ['Asian cuisine', 'Healthy and vegetarian options', 'Reservation recommended'],
    crowdLevel: 'moderate',
    seatAvailability: 'limited',
    entranceFee: '$50-100',
    visitDuration: '2 hrs',
    description: 'An upscale sushi spot for a slower, fine-dining lunch or dinner.',
  },
  'pl-bati-bar-grill': {
    id: 'pl-bati-bar-grill',
    name: 'Bati Bar & Grill',
    category: 'Restaurant',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/bati-bar-grill-pp/640/480',
    mapsLink: 'https://maps.app.goo.gl/HzHK4PZTgDSqTZgP6',
    x: 55, y: 30,
    atmosphere: ['Luxury', 'Fine dining', 'Premium'],
    preferenceMatch: ['Food', 'Meeting friends'],
    keywords: ['Asian, western and khmer menu', 'Full bar', 'Best for a celebration dinner'],
    crowdLevel: 'moderate',
    seatAvailability: 'limited',
    entranceFee: '$8-220',
    visitDuration: '2.5 hrs',
    description: 'A high-end grill and bar built for a celebratory night out, with a menu that spans cuisines.',
  },
  'pl-white-mansion': {
    id: 'pl-white-mansion',
    name: 'Le Cafe at White Mansion',
    category: 'Cafe',
    district: 'Daun Penh',
    image: 'https://picsum.photos/seed/le-cafe-white-mansion-pp/640/480',
    mapsLink: 'https://maps.app.goo.gl/UkPVqAK3h27KVQvv6',
    x: 62, y: 48,
    atmosphere: ['Scenic', 'Lively', 'Cultural'],
    preferenceMatch: ['Relaxing', 'Photography'],
    keywords: ['Colonial-era mansion setting', 'Open 7am-9pm', 'Western food and desserts'],
    crowdLevel: 'quiet',
    seatAvailability: 'plenty',
    entranceFee: '$1-20',
    visitDuration: '1 hr',
    description: 'A restored colonial mansion turned cafe, elegant enough for a mid-afternoon pause.',
  },
}

// ── Trips ─────────────────────────────────────────────────────────────────
export const TRIPS = {
  't-highlights': {
    id: 't-highlights',
    title: 'Phnom Penh Highlights',
    cover: beach,
    status: 'upcoming',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    travelers: 2,
    budget: '$$ Moderate',
    pace: 'Balanced',
    tags: ['Culture', 'Food', 'Riverside'],
    published: true,
    likes: 41,
    comments: 6,
    views: 302,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: '2026-10-10',
        slots: {
          morning: [{ placeId: 'pl-pagoda', time: '8:30 AM' }],
          afternoon: [{ placeId: 'pl-riverside', time: '2:00 PM' }],
          evening: [{ placeId: 'pl-nightmarket', time: '7:00 PM' }],
        },
      },
      {
        label: 'Day 2',
        date: '2026-10-11',
        slots: {
          morning: [{ placeId: 'pl-lotusgarden', time: '7:30 AM' }],
          afternoon: [{ placeId: 'pl-cafe', time: '1:00 PM' }],
          evening: [{ placeId: 'pl-rivergrill', time: '6:30 PM' }],
        },
      },
      {
        label: 'Day 3',
        date: '2026-10-12',
        slots: {
          morning: [{ placeId: 'pl-ricefields', time: '8:00 AM' }],
          afternoon: [],
          evening: [],
        },
      },
    ],
    suggestedAddOn: 'pl-siemreap',
  },
  't-foodcrawl': {
    id: 't-foodcrawl',
    title: 'Riverside Food Crawl',
    cover: foodTable,
    status: 'saved',
    startDate: null,
    endDate: null,
    travelers: 1,
    budget: '$ Budget-friendly',
    pace: 'Packed',
    tags: ['Food', 'Riverside'],
    published: true,
    likes: 19,
    comments: 3,
    views: 140,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: null,
        slots: {
          morning: [{ placeId: 'pl-cafe', time: '9:00 AM' }],
          afternoon: [{ placeId: 'pl-riverside', time: '3:00 PM' }],
          evening: [{ placeId: 'pl-nightmarket', time: '7:30 PM' }],
        },
      },
    ],
  },
  't-templesweekend': {
    id: 't-templesweekend',
    title: 'Temples & Gardens Weekend',
    cover: templeGarden,
    status: 'past',
    startDate: '2026-06-06',
    endDate: '2026-06-07',
    travelers: 3,
    budget: '$$ Moderate',
    pace: 'Relaxed',
    tags: ['Culture', 'Nature'],
    published: true,
    likes: 64,
    comments: 9,
    views: 511,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: '2026-06-06',
        slots: {
          morning: [{ placeId: 'pl-pagoda', time: '7:00 AM' }],
          afternoon: [{ placeId: 'pl-lotusgarden', time: '2:00 PM' }],
          evening: [{ placeId: 'pl-riverside', time: '6:00 PM' }],
        },
      },
      {
        label: 'Day 2',
        date: '2026-06-07',
        slots: {
          morning: [{ placeId: 'pl-ricefields', time: '8:00 AM' }],
          afternoon: [],
          evening: [],
        },
      },
    ],
  },
  't-cafehop': {
    id: 't-cafehop',
    title: "Sreymom's BKK1 Cafe Hop",
    cover: restaurant,
    status: 'saved',
    startDate: null,
    endDate: null,
    travelers: 1,
    budget: '$ Budget-friendly',
    pace: 'Relaxed',
    tags: ['Cafes', 'Work-friendly'],
    published: false,
    likes: 27,
    comments: 4,
    views: 88,
    fromCommunity: true,
    savedFrom: 'Sreymom Chan',
    days: [
      {
        label: 'Day 1',
        date: null,
        slots: {
          morning: [{ placeId: 'pl-cafe', time: '9:30 AM' }],
          afternoon: [],
          evening: [],
        },
      },
    ],
  },

  // ── AI Planner trip packages — offered after a prompt/guided submission.
  // Two free, one paid (gated by PACKAGES[].price below).
  't-pkg-bkk1': {
    id: 't-pkg-bkk1',
    title: 'BKK1 Cafe & Culture Crawl',
    cover: 'https://picsum.photos/seed/bkk1-crawl-cover/900/600',
    status: 'saved',
    startDate: null,
    endDate: null,
    travelers: 2,
    budget: '$ Budget-friendly',
    pace: 'Balanced',
    tags: ['Food', 'Culture', 'Shopping'],
    published: false,
    likes: 0,
    comments: 0,
    views: 0,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: null,
        slots: {
          morning: [{ placeId: 'pl-eleven-one', time: '8:00 AM' }, { placeId: 'pl-langka-lane', time: '10:30 AM' }],
          afternoon: [{ placeId: 'pl-baitong', time: '1:30 PM' }],
          evening: [{ placeId: 'pl-bkk-market', time: '5:30 PM' }],
        },
      },
    ],
  },
  't-pkg-daunpenh': {
    id: 't-pkg-daunpenh',
    title: 'Daun Penh Heritage Day',
    cover: 'https://picsum.photos/seed/daun-penh-heritage-cover/900/600',
    status: 'saved',
    startDate: null,
    endDate: null,
    travelers: 2,
    budget: '$$ Moderate',
    pace: 'Balanced',
    tags: ['Culture', 'Sightseeing', 'Food'],
    published: false,
    likes: 0,
    comments: 0,
    views: 0,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: null,
        slots: {
          morning: [{ placeId: 'pl-royal-palace', time: '8:00 AM' }, { placeId: 'pl-national-museum', time: '10:30 AM' }],
          afternoon: [{ placeId: 'pl-romdeng', time: '1:00 PM' }],
          evening: [{ placeId: 'pl-central-market', time: '5:00 PM' }],
        },
      },
    ],
  },
  't-pkg-premium': {
    id: 't-pkg-premium',
    title: 'Premium Riverside & Fine Dining',
    cover: 'https://picsum.photos/seed/premium-riverside-cover/900/600',
    status: 'saved',
    startDate: null,
    endDate: null,
    travelers: 2,
    budget: '$$$ Premium',
    pace: 'Relaxed',
    tags: ['Food', 'Riverside', 'Luxury'],
    published: false,
    likes: 0,
    comments: 0,
    views: 0,
    fromCommunity: false,
    days: [
      {
        label: 'Day 1',
        date: null,
        slots: {
          morning: [{ placeId: 'pl-gather-grounds', time: '9:00 AM' }, { placeId: 'pl-white-mansion', time: '11:00 AM' }],
          afternoon: [{ placeId: 'pl-sushi-lab', time: '1:30 PM' }],
          evening: [{ placeId: 'pl-bati-bar-grill', time: '7:00 PM' }],
        },
      },
    ],
  },
}

// ── AI Planner trip packages — 2 free, 1 paid ───────────────────────────────
export const PACKAGES = [
  {
    id: 'pkg-bkk1',
    tripId: 't-pkg-bkk1',
    name: 'BKK1 Cafe & Culture Crawl',
    tagline: 'Casual khmer food, a lively lane, dessert and a local market — all in BKK1.',
    price: 0,
    days: 1,
  },
  {
    id: 'pkg-daunpenh',
    tripId: 't-pkg-daunpenh',
    name: 'Daun Penh Heritage Day',
    tagline: 'Royal Palace, the National Museum, a Khmer lunch and Central Market.',
    price: 0,
    days: 1,
  },
  {
    id: 'pkg-premium',
    tripId: 't-pkg-premium',
    name: 'Premium Riverside & Fine Dining',
    tagline: 'Riverside cafes, an upscale sushi lunch and a celebration dinner at Bati Bar & Grill.',
    price: 6.99,
    days: 1,
  },
]

export const BADGES = [
  { id: 'b-explorer', name: 'Explorer', description: 'Visit 10 different places from your itineraries.', icon: 'compass', unlocked: true },
  { id: 'b-photographer', name: 'Photographer', description: 'Post 5 photo posts to the forum.', icon: 'camera', unlocked: true },
  { id: 'b-foodhunter', name: 'Food Hunter', description: 'Add 8 restaurants or food stalls to a trip.', icon: 'utensils', unlocked: true },
  { id: 'b-culturelover', name: 'Culture Lover', description: 'Visit 5 temples or heritage sites.', icon: 'landmark', unlocked: false, requirement: '3 / 5 visited' },
  { id: 'b-communitystar', name: 'Community Star', description: 'Receive 100 likes across your shared trips.', icon: 'star', unlocked: false, requirement: '61 / 100 likes' },
  { id: 'b-planner', name: 'Planner', description: 'Publish 5 trips to the community.', icon: 'map', unlocked: true },
]

// ── Forum ─────────────────────────────────────────────────────────────────
export const FORUM_AUTHORS = {
  'sreymom.kh': { username: 'sreymom.kh', displayName: 'Sreymom Chan', location: 'Phnom Penh, Cambodia', bio: 'Slow travel, fast street food. I post the trips I actually took.', travelStyleTags: ['Culture Lover', 'Solo Traveler'], stats: { tripsPublished: 9, placesVisited: 58, tripsLiked: 34 }, followers: 340, following: 112, isFollowing: false },
  'vichet.rides': { username: 'vichet.rides', displayName: 'Vichet Ros', location: 'Phnom Penh, Cambodia', bio: 'Tuk-tuk routes, hidden alleys, and where to catch the breeze.', travelStyleTags: ['Local Guide', 'Night Owl'], stats: { tripsPublished: 4, placesVisited: 71, tripsLiked: 21 }, followers: 512, following: 88, isFollowing: true },
  'bopha.eats': { username: 'bopha.eats', displayName: 'Bopha Sok', location: 'Phnom Penh, Cambodia', bio: 'Documenting every stall in the night market, one skewer at a time.', travelStyleTags: ['Foodie', 'Photographer'], stats: { tripsPublished: 5, placesVisited: 39, tripsLiked: 47 }, followers: 289, following: 143, isFollowing: false },
  'chenda.journal': { username: 'chenda.journal', displayName: 'Chenda Pich', location: 'Phnom Penh, Cambodia', bio: 'Community events, local markets, and weekend pop-ups.', travelStyleTags: ['Community Builder'], stats: { tripsPublished: 3, placesVisited: 22, tripsLiked: 15 }, followers: 176, following: 64, isFollowing: true },
  'ratanak.photo': { username: 'ratanak.photo', displayName: 'Ratanak Heng', location: 'Siem Reap, Cambodia', bio: 'Landed in Phnom Penh, planning my way through the south.', travelStyleTags: ['Backpacker'], stats: { tripsPublished: 2, placesVisited: 14, tripsLiked: 9 }, followers: 64, following: 51, isFollowing: false },
}

export const FORUM_POSTS = [
  {
    id: 'fp-1',
    type: 'trip',
    author: 'sreymom.kh',
    date: '2026-09-14',
    tripId: 't-templesweekend',
    caption: 'Two days of temples and gardens with my sisters. We didn\'t rush a single stop.',
    likes: 64,
    comments: [
      { id: 'c1', author: 'bopha.eats', text: 'The lotus garden photos are gorgeous, adding this to my list.' },
      { id: 'c2', author: 'vichet.rides', text: 'Best time to go is right at opening, before the tour buses.' },
    ],
  },
  {
    id: 'fp-2',
    type: 'discussion',
    author: 'vichet.rides',
    date: '2026-09-16',
    title: 'Best time of day to visit the riverside without the crowds?',
    body: 'Every itinerary I see sends people to Sisowath Quay right at sunset, which means everyone is there at once. Anyone found a quieter window?',
    tags: ['riverside', 'tips'],
    likes: 22,
    comments: [
      { id: 'c3', author: 'sreymom.kh', text: 'Early morning around 6am, before the joggers even show up.' },
    ],
  },
  {
    id: 'fp-3',
    type: 'photo',
    author: 'bopha.eats',
    date: '2026-09-15',
    caption: 'One full lap of the night market stalls. Still thinking about the grilled skewers.',
    location: 'Night Market Food Court',
    photos: [foodTable, restaurant, foodTable, restaurant, foodTable],
    likes: 88,
    comments: [
      { id: 'c4', author: 'chenda.journal', text: 'That skewer stall on the corner is unbeatable.' },
    ],
  },
  {
    id: 'fp-4',
    type: 'poll',
    author: 'dara.explores',
    date: '2026-09-17',
    question: 'Which day-trip should I add to my 3-day itinerary?',
    options: [
      { id: 'o1', label: 'Countryside rice fields', votes: 34 },
      { id: 'o2', label: 'Siem Reap extension', votes: 51 },
      { id: 'o3', label: 'Stay in the city', votes: 12 },
    ],
    likes: 14,
    comments: [],
  },
  {
    id: 'fp-5',
    type: 'event',
    author: 'chenda.journal',
    date: '2026-09-13',
    title: 'Riverside Night Market: Craft Vendors Pop-up',
    eventDate: '2026-09-27',
    eventTime: '5:00 PM - 10:00 PM',
    location: 'Sisowath Quay, near the Night Market',
    body: 'Local makers selling jewelry, textiles, and small prints. First time running this alongside the usual food stalls.',
    likes: 31,
    comments: [],
  },
  {
    id: 'fp-6',
    type: 'status',
    author: 'ratanak.photo',
    date: '2026-09-18',
    body: 'Just landed in Phnom Penh, itinerary generated in about two minutes flat. Impressed.',
    likes: 9,
    comments: [],
  },
  {
    id: 'fp-7',
    type: 'trip',
    author: 'dara.explores',
    date: '2026-09-12',
    tripId: 't-foodcrawl',
    caption: 'Published my food crawl route for anyone visiting on a tight budget.',
    likes: 27,
    comments: [
      { id: 'c5', author: 'bopha.eats', text: 'Saving this for my next trip back.' },
    ],
  },
  {
    id: 'fp-8',
    type: 'discussion',
    author: 'sreymom.kh',
    date: '2026-09-11',
    title: 'Guided mode vs prompt mode: which do you use?',
    body: 'I default to guided mode because I like locking in the budget up front, but curious if prompt mode users get better results.',
    tags: ['planner', 'tips'],
    likes: 18,
    comments: [
      { id: 'c6', author: 'ratanak.photo', text: 'Prompt mode for me, feels faster when I already know the vibe I want.' },
    ],
  },
]

export const LIKED_TRIPS = [
  { title: 'Temples & Gardens Weekend', creator: 'sreymom.kh', cover: templeGarden, tags: ['Culture', 'Nature'] },
  { title: 'Late Night Riverside Grill Tour', creator: 'vichet.rides', cover: foodTable, tags: ['Food', 'Nightlife'] },
  { title: 'Rainy Season Market Crawl', creator: 'bopha.eats', cover: restaurant, tags: ['Food', 'Market'] },
]

export const CROWD_LABELS = {
  quiet: { label: 'Quiet', hint: 'Good time to visit' },
  moderate: { label: 'Moderate', hint: 'Some wait possible' },
  busy: { label: 'Busy', hint: 'Expect a line' },
}
